### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by aboeglin** [hdeshev/express-typescript#3]
Could you maybe add the types in the functions of your routes ? I wanted to see how you use them but you don't define any of them. Therefore it's just about writing javascript in a .ts it seems. You'd call them directly .js you could avoid the compilation.

**Comment by hdeshev** [comment]
This is an old example written 3 years ago that showcases writing "real" apps with TypeScript outside the usual Visual Studio ecosystem using a popular Linux toolchain. I didn't focus on the actual Express API and its types at all.
